home:
     path: /
     methods: [GET]
     defaults: { _controller: AppBundle:Default:index}

ask:
    path: /ask
    methods: [GET,POST]
    defaults: { _controller: AppBundle:Question:ask}

all:
    path: /all
    methods: [GET]
    defaults: { _controller: AppBundle:Question:all}

view:
    path: /{slug}/view
    methods: [GET,POST]
    defaults: { _controller: AppBundle:Question:view }

unanswered:
    path: /unanswered
    methods: [GET]
    defaults: { _controller: AppBundle:Question:unanswered}