home:
     path: /{_locale}
     methods: [GET]
     defaults: { _controller: AppBundle:Default:index, _locale: ua}
     requirements:
             _locale: en|ua
ask:
    path: /ask/{_locale}
    methods: [GET,POST]
    defaults: { _controller: AppBundle:Question:ask, _locale: ua}
    requirements:
             _locale: en|ua
all:
    path: /all/{_locale}
    methods: [GET]
    defaults: { _controller: AppBundle:Question:all, _locale: ua}
    requirements:
             _locale: en|ua

view:
    path: /{slug}/view/{_locale}
    methods: [GET,POST]
    defaults: { _controller: AppBundle:Question:view, _locale: ua }
    requirements:
             _locale: en|ua

unanswered:
    path: /unanswered/{_locale}
    methods: [GET]
    defaults: { _controller: AppBundle:Question:unanswered, _locale: ua}
    requirements:
             _locale: en|ua

tags:
    path: /tags/{_locale}
    methods: [GET]
    defaults: { _controller: AppBundle:Tag:index, _locale: ua}
    requirements:
             _locale: en|ua

view_tag:
    path: /{slug}/tag_view/{_locale}
    methods: [GET]
    defaults: { _controller: AppBundle:Tag:view, _locale: ua}
    requirements:
             _locale: en|ua

registration:
     path: /registration
     methods: [GET,POST]
     defaults: { _controller: AppBundle:User:registration, _locale: ua}
     requirements:
            _locale: en|ua

login:
     path: /login
     methods: [GET,POST]
     defaults: { _controller: AppBundle:User:login, _locale: ua}
     requirements:
            _locale: en|ua

logout:
     path: /logout
     methods: [GET]
     defaults: { _controller: AppBundle:User:logout, _locale: ua}
     requirements:
            _locale: en|ua

questions:
    path: /questions
    methods: [GET]
    defaults: { _controller: AppBundle:User:questions, _locale: ua}
    requirements:
           _locale: en|ua